apiVersion: v1
kind: Service
metadata:
  name: {{ include "plinth.fullname" . }}
  labels:
    {{- include "plinth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "plinth.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
