// SPDX-License-Identifier: MIT
//
// Ordinary regression cases for the ICD-0.3.2 randomBytes integer contract.
// The generated bytes are intentionally not compared: only their type and
// length are deterministic. All inputs are fake and the test needs no DB.

#include <catch2/catch_test_macros.hpp>

#include "kernel/config.hpp"
#include "kernel/js/eval.hpp"
#include "kernel/js/runtime_pool.hpp"

#include <array>
#include <chrono>
#include <cstddef>
#include <string>
#include <string_view>

using namespace std::chrono_literals;

namespace {

struct NumericCase {
  std::string_view argument;
  std::string_view expected;
};

// Preserve the distinction between malformed numbers (TypeError) and
// integral numbers outside [1, 4096] (RangeError), including values that
// JS_ToInt32 would wrap into the accepted range.
constexpr std::array CASES{
    NumericCase{"1", "ok:1"},
    NumericCase{"4096", "ok:4096"},
    NumericCase{"", "error:TypeError"},
    NumericCase{"undefined", "error:TypeError"},
    NumericCase{"true", "error:TypeError"},
    NumericCase{"'1'", "error:TypeError"},
    NumericCase{"null", "error:TypeError"},
    NumericCase{"({})", "error:TypeError"},
    NumericCase{"new Number(1)", "error:TypeError"},
    NumericCase{"1n", "error:TypeError"},
    NumericCase{"1.5", "error:TypeError"},
    NumericCase{"-1.5", "error:TypeError"},
    NumericCase{"4095.5", "error:TypeError"},
    NumericCase{"4096.5", "error:TypeError"},
    NumericCase{"NaN", "error:TypeError"},
    NumericCase{"Infinity", "error:TypeError"},
    NumericCase{"-Infinity", "error:TypeError"},
    NumericCase{"Number.MIN_VALUE", "error:TypeError"},
    NumericCase{"0", "error:RangeError"},
    NumericCase{"-0", "error:RangeError"},
    NumericCase{"-1", "error:RangeError"},
    NumericCase{"4097", "error:RangeError"},
    NumericCase{"2147483648", "error:RangeError"},
    NumericCase{"4294967296", "error:RangeError"},
    NumericCase{"4294967297", "error:RangeError"},
    NumericCase{"-4294967295", "error:RangeError"},
    NumericCase{"9007199254740992", "error:RangeError"},
    NumericCase{"Number.MAX_VALUE", "error:RangeError"},
};

auto classify(std::string_view argument) -> std::string {
  return "(() => { try { const value = crypto.randomBytes(" +
         std::string{argument} +
         "); return value instanceof Uint8Array ? 'ok:' + value.length : "
         "'wrong-type'; } catch (error) { return 'error:' + error.name + "
         "'|' + error.message; } "
         "})()";
}

auto expected_output(std::string_view expected) -> std::string {
  if (expected == "error:TypeError") {
    return "error:TypeError|crypto.randomBytes: expected integer at arg 0";
  }
  if (expected == "error:RangeError") {
    return "error:RangeError|crypto.randomBytes: n out of range [1, 4096]";
  }
  return std::string{expected};
}

} // namespace

TEST_CASE("crypto.randomBytes enforces strict integer and range boundaries",
          "[js][stdlib][crypto][numeric-regression]") {
  plinth::Config config{};
  plinth::js::RuntimePool pool(nullptr, plinth::js::default_runtime_limits(),
                               config, 1);

  for (std::size_t index = 0; index < CASES.size(); ++index) {
    const auto& item = CASES[index];
    INFO("case=" << index << " argument=" << item.argument);
    auto* context = pool.acquire();
    REQUIRE(context != nullptr);

    const auto result =
        plinth::js::eval_on_context(*context, classify(item.argument));
    // Check recovery on the same context before reset. Capture the result
    // first, then return the lease before any assertion can unwind the test.
    const auto follow_up =
        plinth::js::eval_on_context(*context, "crypto.randomBytes(1).length");

    if (index % 2 == 0) {
      pool.release(context);
    } else {
      pool.destroy(context);
    }
    REQUIRE(result.has_value());
    REQUIRE(result->isString());
    REQUIRE(result->asString() == expected_output(item.expected));
    REQUIRE(follow_up.has_value());
    REQUIRE(follow_up->asInt() == 1);
    if (index % 8 == 7) {
      pool.rebuild();
    }
  }

  REQUIRE(pool.active_count() == 0);
  REQUIRE(pool.shutdown(2s));
  REQUIRE(pool.acquire() == nullptr);
}
