version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /load-harness
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 5
